author: Jianwei Han
url: http://ds-class.github.io
title: 数据结构

pygments: true
markdown: redcarpet

redcarpet:
  extensions: [no_intra_emphasis, tables, fenced_code_blocks, autolink, space_after_headers]
